### PR TITLE
Suggestion - Reorder Intro to Ruby a bit

### PR DESCRIPTION
**Pull request by CheezItMan**
## Description

Small issue since it's a review of Jumpstart, but we've got if statements in the [Iteration & Blocks](https://github.com/Ada-Developers-Academy/textbook-curriculum/blob/master/01-ruby-fundamentals/iteration-and-blocks.md) lecture before we cover comparison & flow control.  Same thing for the 

Don't know why I didn't notice it before, probably because I was looking at the the lectures in isolation.

## Feedback Requested
Please utilize the built-in GitHub Reviewers functionality to assign necessary reviewers. Use this section to further specify portions of the PR that you would like additional or focused feedback on.

### CODE REVIEW

**Comment by kariabancroft** [comment]
In your description you write "Same thing for"... is there another instance of this or are we good with this one adjustment?

**Comment by droberts-ada** [comment]
Probably the loop table worksheet?

**Comment by CheezItMan** [comment]
Sorry yes, loop tables worksheet.

Also I need to move that worksheet to the exercises folder.

**Comment by kariabancroft** [comment]
@CheezItMan Do you want to make these changes as part of this PR or should we just merge in this one change?

**Comment by CheezItMan** [comment]
@kariabancroft lets just do this as this PR.

**Comment by CheezItMan** [comment]
I've updated the PR.

**Pull request merged**
