### PR TITLE
Cm/user stories

### PR DESCRIPTION
**Pull request by CheezItMan**
## Description

I've setup a basic doc on user stories.  There is an accompanying lesson plan on the teacher's edition.  We'll start by introducing the need to gather requirements for a project, and then watch a short (5 min) video on user stories.  

Then we'll have them write their own  on notecards provided.  Then review one group's stories.

### CODE REVIEW

**Comment by droberts-ada** [comment]
Could you talk a little about why you would structure project requirements in user stories? Maybe tie it into some of the concepts they've been getting from the Metz reading - change is constant, customers don't know what they want at the beginning, monolithic design is bad but incremental design works well, etc.

**Comment by CheezItMan** [comment]
@droberts-ada Sure, I'd held off since this wasn't an Agile lecture, but rather focused on user stories.  

Building it now.

**Comment by CheezItMan** [comment]
I'm thinking 30 minutes 5 minutes talk, 5 minutes video, and then 10 minutes personal user stories with a bit of a close.  So I don't THINK it'll take much more than 30 minutes.

**Comment by droberts-ada** [comment]
Looks good

**Pull request merged**
