### PR TITLE
print out postgres status and run rails db:create

### PR DESCRIPTION
**Pull request by CheezItMan**
## Description
Just a small update to the rails template letting us output the status of postgres (letting us know if it's not installed or the service is in an error state, and running `rails db:create` to automatically create the database to start with.  

## Questions for the Author
- [NA ] Have you updated the weekly learning goals in the pedagogy resource?
- [NA ] Have you updated the weekly assessment in Schoology?
- [NA ] Have you added links to the source (lucidchart, draw.io) for any diagram?
- [NA ] Have you updated the READMEs with links to new or moved resources?

## Todos
None

## Feedback Requested
Please utilize the built-in GitHub Reviewers functionality to assign necessary reviewers. Use this section to further specify portions of the PR that you would like additional or focused feedback on.

### CODE REVIEW

**Comment by droberts-ada** [comment]
Aren't there two versions of the Rails template? You should make sure to update both of them.

**Comment by CheezItMan** [comment]
Doh, I'd thought we stopped using 2 templates and just set up one to use for the entire unit.  I've updated both.

**Comment by droberts-ada** [comment]
OK, here's another question. Making it so they don't have to run `rails db:create` after running `rails new` is only useful for a couple projects. Anything where we give them some starter code, or any pair project, they'll still have to do it. So, it might be cleaner / more consistent to just make them do it all the time.

**Comment by CheezItMan** [comment]
Ok I've removed `rails db:create`

**Pull request merged**
